#ifndef KINECT_VALS_H
#define KINECT_VALS_H

#define HANDSTATE_UNKNOWN    0
#define HANDSTATE_NOTTRACKED 1
#define HANDSTATE_OPEN       2
#define HANDSTATE_CLOSED     3
#define HANDSTATE_LASSO      4

#define JOINTTYPE_SPINEBASE	    0
#define JOINTTYPE_SPINEMID	    1
#define JOINTTYPE_NECK	        2
#define JOINTTYPE_HEAD	        3
#define JOINTTYPE_SHOULDERLEFT  4
#define JOINTTYPE_ELBOWLEFT	    5
#define JOINTTYPE_WRISTLEFT	    6
#define JOINTTYPE_HANDLEFT	    7
#define JOINTTYPE_SHOULDERRIGHT 8
#define JOINTTYPE_ELBOWRIGHT    9
#define JOINTTYPE_WRISTRIGHT    10
#define JOINTTYPE_HANDRIGHT	    11
#define JOINTTYPE_HIPLEFT	    12
#define JOINTTYPE_KNEELEFT	    13
#define JOINTTYPE_ANKLELEFT	    14
#define JOINTTYPE_FOOTLEFT	    15
#define JOINTTYPE_HIPRIGHT	    16
#define JOINTTYPE_KNEERIGHT	    17
#define JOINTTYPE_ANKLERIGHT    18
#define JOINTTYPE_FOOTRIGHT	    19
#define JOINTTYPE_SPINESHOULDER 20
#define JOINTTYPE_HANDTIPLEFT   21
#define JOINTTYPE_THUMBLEFT	    22
#define JOINTTYPE_HANDTIPRIGHT  23
#define JOINTTYPE_THUMBRIGHT    24
#define JOINTTYPE_COUNT	        (JOINTTYPE_THUMBRIGHT + 1)

#endif