uint8 SPINEBASE     = 0
uint8 SPINEMID      = 1
uint8 NECK          = 2
uint8 HEAD          = 3
uint8 SHOULDERLEFT  = 4
uint8 ELBOWLEFT     = 5
uint8 WRISTLEFT     = 6
uint8 HANDLEFT      = 7
uint8 SHOULDERRIGHT = 8
uint8 ELBOWRIGHT    = 9
uint8 WRISTRIGHT    = 10
uint8 HANDRIGHT     = 11
uint8 HIPLEFT       = 12
uint8 KNEELEFT      = 13
uint8 ANKLELEFT     = 14
uint8 FOOTLEFT      = 15
uint8 HIPRIGHT      = 16
uint8 KNEERIGHT     = 17
uint8 ANKLERIGHT    = 18
uint8 FOOTRIGHT     = 19
uint8 SPINESHOULDER = 20
uint8 HANDTIPLEFT   = 21
uint8 THUMBLEFT     = 22
uint8 HANDTIPRIGHT  = 23
uint8 THUMBRIGHT    = 24
uint8 COUNT         = 25

Header header
uint32 id
geometry_msgs/Pose[] joints
